import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/Components/Navbar/Navbar";
import { Poppins, Inter, Ballet } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--next-font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--next-font-inter",
});

const ballet = Ballet({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--next-font-ballet",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`w-screen ${poppins.variable} ${inter.variable} ${ballet.variable} font-sans bg-[#f9f9f9]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
